# サーバーはトランザクションを再開できませんでした。

com.microsoft.sqlserver.jdbc.SQLServerException: サーバーはトランザクションを再開できませんでした。

The server failed to resume the transaction

## 原因

黨通過jdbc Connection.setAutoCommit(false) 或者通過執行t-sql語句 BEGIN TRANSACTION statement

就會在當前的Connection中開啓transaction，直到它被commit或rollback，才會結束transaction。 SQL Server 通过在事务启动时将transaction ID 传回驱动程序并要求驱动程序在执行后续语句时将该transaction ID 传回服务器来强制 JDBC 驱动程序等驱动程序遵守该合同。如果在事务提交或回滚后驱动程序继续使用事务 ID，则会出现“サーバーはトランザクションを再開できませんでした。The server failed to resume the transaction”的错误

那jdbc driver是怎麽和服務器傳遞管理transaction ID的呢，SQL Server 通過查询的执行结果（更新计数、结果集、错误）向驱动程序发送“事务已启动”和“事务回滚/提交”消息。在Server發送处理结果給jdbc driver之前，驱动程序无法“看到”这些消息，也就無法知道，transaction是commit了，還是rollback了。所以一旦事务开始，如果sql语句的执行會导致提交或回滚，驱动程序会认为事务仍然处于活动状态，直到sql语句的结果被發送到jdbc driver。

## 對策

1. 在同一连接上要等待所有执行结果被處理之後，再执行另一条语句。尤其是不要再另一个线程上同時執行sql statement。如果您的语句不仅仅是简单的 INSERT、UPDATE 或 DELETE，请使用 Statement.execute() 来执行它，并使用 Statement.getMoreResults() 来遍历结果。
2. 如果您对执行结果不感兴趣，您需要调用 Statement.close()。
3. 避免将 JDBC API 事务控制（连接方法：setAutoCommit、commit、rollback）与 T-SQL 事务控制语句（BEGIN TRAN， commit TRAN， rollback  TRAN）混合用。如果可能，完全避免 T-SQL 事务控制，尤其是嵌套事务语句。如果存储过程在嵌套事务中执行了意外的 ROLLBACK，则可能难以定位。
4. 了解 SQL Server 有时会出于自身原因回滚事务。其中一个原因是类型转换错误。例如：如果表列是 INTEGER，则 INSERT INTO myTable VALUES ('bar') 将回滚事务，因为 SQL Server 不知道如何将文字值 'bar' 转换为 INTEGER。

## 例  con.commit(); // This commits the transaction and starts a new one.

```java
public static void executeTransaction(Connection con) {
    try {
        //Switch to manual transaction mode by setting
        //autocommit to false. Note that this starts the first 
        //manual transaction.
        con.setAutoCommit(false);
        Statement stmt = con.createStatement();
        stmt.executeUpdate("INSERT INTO Production.ScrapReason(Name) VALUES('Wrong size')");
        stmt.executeUpdate("INSERT INTO Production.ScrapReason(Name) VALUES('Wrong color')");
        stmt.close(); // This turns off the Statement避免用舊的transaction id 繼續執行 sql Statement.
        con.commit(); // This commits the transaction and starts a new one.
        System.out.println("Transaction succeeded. Both records were written to the database.");
    }
    catch (SQLException ex) {
        ex.printStackTrace();
        try {
            System.out.println("Transaction failed.");
            con.rollback();
        }
        catch (SQLException se) {
            se.printStackTrace();
        }
    }
}
```





